<script setup lang="ts">
import { listUnreadAnnouncements, markAnnouncementRead, type Announcement } from "@/services/apis/announcement";
import { useAppStateStore } from "@/stores/useAppStateStore";
import { computed, ref, watch } from "vue";

const { state } = useAppStateStore();
const unread = ref<Announcement[]>([]); const visible = ref(false); const submitting = ref(false);
const current = computed(() => unread.value[0]);
const loadUnread = async () => { if (!state.userInfo?.token) return; try { const result = await listUnreadAnnouncements().execute({ forceRequest: true }); unread.value = (result.value ?? []).filter((item) => item.active !== false); visible.value = unread.value.length > 0; } catch (error) { console.warn("Unable to load unread announcements", error); } };
const confirmRead = async () => { if (!current.value) return; submitting.value = true; try { await markAnnouncementRead().execute({ data: { id: current.value.id }, forceRequest: true }); unread.value.shift(); visible.value = unread.value.length > 0; } finally { submitting.value = false; } };
watch(() => state.userInfo?.token, (token, oldToken) => { if (token && token !== oldToken) void loadUnread(); if (!token) { unread.value=[]; visible.value=false; } }, { immediate: true });
</script>
<template><a-modal class="announcement-dialog" :open="visible" :closable="false" :mask-closable="false" :keyboard="false" centered :width="560"><template #title><div class="dialog-title"><span>新公告</span><a-tag class="unread-tag">{{ unread.length }} 条未读</a-tag></div></template><div v-if="current" class="dialog-content"><div class="sequence">ANNOUNCEMENT · {{ unread.length > 1 ? `还有 ${unread.length - 1} 条` : "最后一条" }}</div><h2>{{ current.title }}</h2><div class="announcement-copy">{{ current.content }}</div><div v-if="unread.length > 1" class="up-next"><span>接下来</span><ol><li v-for="item in unread.slice(1,4)" :key="item.id">{{ item.title }}</li></ol></div></div><template #footer><a-button type="primary" :loading="submitting" @click="confirmRead">{{ unread.length > 1 ? "我已阅读，查看下一条" : "我已阅读" }}</a-button></template></a-modal></template>
<style scoped lang="scss">.announcement-dialog :deep(.ant-modal-content),.announcement-dialog :deep(.ant-modal-header),.announcement-dialog :deep(.ant-modal-body),.announcement-dialog :deep(.ant-modal-footer){background:transparent !important}.announcement-dialog :deep(.ant-modal-content){overflow:hidden;border-radius:18px !important}.announcement-dialog :deep(.ant-modal-footer){border-top:1px solid var(--border-subtle) !important}.dialog-title{display:flex;align-items:center;justify-content:space-between;padding-right:22px}.dialog-content{padding:4px 2px 10px}.unread-tag{color:var(--accent-primary);border-color:var(--border-default);background:var(--accent-soft)}.sequence{color:var(--accent-primary);font-size:11px;font-weight:700;letter-spacing:.1em}h2{margin:10px 0 14px;font-size:24px}.announcement-copy{max-height:42vh;overflow-y:auto;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.8;opacity:.82}.up-next{margin-top:20px;padding:12px 14px;border-radius:10px;background:var(--surface-inner);border:1px solid var(--border-subtle);font-size:12px}.up-next span{font-weight:700;opacity:.65}.up-next ol{margin:6px 0 0;padding-left:18px;opacity:.68}</style>
